### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by ert78gb**

### CODE REVIEW

**Comment by ert78gb** [comment]
Hi @tolbertam,

Do you have time review this PR. 
thx

**Comment by tolbertam** [comment]
Thanks for the ping, somehow I missed the notification.  I'll take a look at this now, thanks!

**Comment by tolbertam** [comment]
LGTM, thanks for the contribution, cheers! :beers:

Will be released as 0.4.1.

**Comment by tolbertam** [comment]
published, thanks!

**Comment by ert78gb** [comment]
thx

**Pull request merged**
